c-final-capstone-team-2/WebApplication.Web/Models/Slot.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication.Web.Models
{
    public class Slot
    {
        public int ID { get; set; } = -1;
        public int TournamentID { get; set; } = -1;
        public int PlayerID { get; set; } = -1;
        public int NextSlotID { get; set; } = -1;
        public double Xpos { get; set; }
        public double Ypos { get; set; }
        public int Score { get; set; }
        private User player = null;
        public User Player
        {
            get
            {
                return player;
            }
            set
            {
                if (value != null)
                {
                    PlayerID = value.Id;
                    player = value;
                }
            }
        }
        private Slot nextSlot = null;
        public Slot NextSlot
        {
            get
            {
                return nextSlot;
            }
            set
            {
                if(value != null)
                {
                    NextSlotID = value.ID;
                    nextSlot = value;
                }
            }
        }
    }
}

c-final-capstone-team-2/WebApplication.Web/ViewComponents/NavBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication.Web.Providers.Auth;

namespace WebApplication.Web.ViewComponents
{
    /// <summary>
    /// A view component is a reusable or "isolated" piece of our app.
    /// It cannot be navigated to via URL like a controller.
    /// </summary>
    public class NavBarViewComponent : ViewComponent
    {
        // Components allow dependency injection just like controllers.
        private IAuthProvider authProvider;
        public NavBarViewComponent(IAuthProvider authProvider)
        {
            this.authProvider = authProvider;
        }

        /// <summary>
        /// This is the method that is invoked when the component is told to "render".
        /// </summary>
        /// <returns></returns>
        public IViewComponentResult Invoke()
        {
            var user = authProvider.GetCurrentUser();
            return View("_NavBar", user);
        }
    }
}

c-final-capstone-team-2/WebApplication.Web/Views/Shared/HostingTourney.cshtml
<link rel="stylesheet" href="~/css/tourneyhome.css" />
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<h2>Hosting</h2>
<form asp-controller="tourney" asp-action="browse" method="post">
    <div>
        <textarea rows="4" cols="50">
            List of hosted Tournaments
            Coming Soon!!
        </textarea>
    </div>
    <div>
        <button class="btn btn-default customT" asp-controller="Tourney" asp-action="SearchUser">Create Tournament</button>
    </div>
    <div>
        <button class="btn btn-info customT" asp-controller="Tourney" asp-action="LocalNumPlayer">Create Local Tournament</button>
    </div>
    <div>
        <button class="btn btn-info customT" asp-controller="Tourney" asp-action="Browse">View Tournament</button>
    </div>
</form>

c-final-capstone-team-2/WebApplication.Web/Views/Shared/JoinedTourney.cshtml
<link rel="stylesheet" href="~/css/tourneyhome.css" />

@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<h2>Joined</h2>
<form asp-controller="tourney" asp-action="browse" method="post">
    <div>
        <textarea rows="4" cols="50">
            List of joined Tournaments
            Coming Soon!!
        </textarea>
    </div>
    <textarea rows="4" cols="50" placeholder="Coming Soon!!">
            List of pending Tournaments
            Coming Soon!!
        </textarea>
    <div>
        <input type="text" name="SearchStr">
        <button class="btn btn-info" asp-controller="Tourney" asp-action="Browse">Search</button>
    </div>  
</form>

c-final-capstone-team-2/WebApplication.Web/Views/Shared/TourneyHome.cshtml
<link rel="stylesheet" href="~/css/tourneyhome.css" />

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h2>Tournaments</h2>
<form asp-controller="tourney" asp-action="browse" method="post">
    <div>
        <button class="btn btn-default customT" asp-controller="Tourney" asp-action="LocalNumPlayer">Create Local Tournament</button>
    </div>
    <div>
        <button class="btn btn-info customT" asp-controller="Tourney" asp-action="Index">View Tourney</button>
    </div>
    <div>
        <input class="customB" type="text" name="SearchStr">
        <button class="btn btn-info" asp-controller="Tourney" asp-action="Browse">Search</button>
    </div>
</form>

c-final-capstone-team-2/WebApplication.Web/Views/Shared/_EmailInvite.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="container" style="max-width:500px">
    <div class="panel-body">
        <form class="form-horizontal" role="form">
            <fieldset>
                <legend>Email Invite</legend>
                <p>Use this method to send an email invitation automatically.</p>&nbsp;

                <div class="form-group">
                    <label for="inputEmail1" class="col-md-4 control-label">Email*</label>
                    <div class="col-md-7">
                        <input type="email" class="form-control" id="inputEmail1" placeholder="Email">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputEmail1" class="col-md-4 control-label">First Name*</label>
                    <div class="col-md-7">
                        <input type="text" class="form-control" placeholder="First Name">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputEmail1" class="col-md-4 control-label" required="">Last Name*</label>
                    <div class="col-md-7">
                        <input type="text" class="form-control" placeholder="Last Name">
                    </div>
                </div>                

                <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-9">
                        <button type="Invite" class="btn btn-primary pull-right">Invite</button>
                    </div>
                </div>

            </fieldset>
        </form>
    </div>
</div>

</div>

c-final-capstone-team-2/WebApplication.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tournament Tracker</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
        <script src="https://unpkg.com/interactjs@1.3.4/dist/interact.min.js"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Tournament Tracker</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>                   

                </ul>

                <ul class="nav navbar-nav navbar-right">
                    @await Component.InvokeAsync("NavBar") @* Render the NavBar component. *@
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="jumbotron jumbotron-fluid">
            <h1>Tournament Tracker</h1>
        </div>
    </div>
    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        @*<hr />
        <footer>
            <p>&copy; 2018 - WebApplication.Web</p>
        </footer>*@
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
        <script src="https://unpkg.com/interactjs@1.3.4/dist/interact.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

c-final-capstone-team-2/WebApplication.Web/Views/Shared/_SlotsView.cshtml
@model List<Slot>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="wrapper">
    @foreach(Slot bracket in Model)
    {
        <div>@bracket.Player</div>
        <hr />
        <div>@bracket.TournamentID</div>
    }
</div>